### ISSUE TITLE
Better Error Message If No Backend Installed

### ISSUE THREAD

**Issue by rmorshea** [reactive-python/reactpy#1042]
### Current Situation

I think a lot of people get confused by this error message: 
![image](https://github.com/reactive-python/reactpy/assets/4041990/6e94b007-d628-40ae-9a8c-6681fa707a25)

### Proposed Actions

We should suggest installing a particular backend in the error message (e.g. `pip install reactpy[starlette]`).

**Comment by geckguy** [comment]
can i work on this issue?

**Comment by Smit-Parmar** [comment]
Sure @geckguy 
@rmorshea Can you please provide step to reproduce?

**Comment by rmorshea** [comment]
Sure. This error happens when you haven't installed any of the built-in backends. For example, if you only run `pip install reactpy` instead of running say, `pip install reactpy[starlette]`. In the case of the former, when you try and use `reactpy.run` to execute your application, you'll see the error shown above.

So really, all we need here is a more detailed message that suggests a solution to the problem rather then just saying that we couldn't find an installed backend. The message in question can be found [here](https://github.com/reactive-python/reactpy/blob/main/src/py/reactpy/reactpy/backend/default.py#L62-L63).

**Comment by geckguy** [comment]
> Sure. This error happens when you haven't installed any of the built-in backends. For example, if you only run `pip install reactpy` instead of running say, `pip install reactpy[starlette]`. In the case of the former, when you try and use `reactpy.run` to execute your application, you'll see the error shown above.
> 
> So really, all we need here is a more detailed message that suggests a solution to the problem rather then just saying that we couldn't find an installed backend. The message in question can be found [here](https://github.com/reactive-python/reactpy/blob/main/src/py/reactpy/reactpy/backend/default.py#L62-L63).

Okay so in the error message should it suggest possible fixes or should it suggest the exact fix for the problem? for instance possible fix could be to suggest a list of commands that might help them fix the problem

**Comment by rmorshea** [comment]
Given that the user, having only installed `reactpy`, probably doesn't care what backend they're using, I think we can specifically suggest that they `pip install "reactpy[starlette]"`. With that said, we can also mention that you can substitute `starlette` for any of the other supported backends using [`reactpy.backend.utils.SUPPORTED_PACKAGES` ](https://github.com/reactive-python/reactpy/blob/f559e230dc1ac846549524dfcb722319adc1e1af/src/py/reactpy/reactpy/backend/utils.py#L16-L22).

**Comment by rmorshea** [comment]
If you're able to get this done in the next day or two we can put this out in a 1.0.1 release.

**Comment by geckguy** [comment]
> Given that the user, having only installed `reactpy`, probably doesn't care what backend they're using, I think we can specifically suggest that they `pip install "reactpy[starlette]"`. With that said, we can also mention that you can substitute `starlette` for any of the other supported backends using [`reactpy.backend.utils.SUPPORTED_PACKAGES` ](https://github.com/reactive-python/reactpy/blob/f559e230dc1ac846549524dfcb722319adc1e1af/src/py/reactpy/reactpy/backend/utils.py#L16-L22).

Got it! i am already on it
