### ISSUE TITLE
Support `configure()` without a `component=...`

### ISSUE THREAD

**Issue by Archmonger** [reactive-python/reactpy#1071]
### Current Situation

All `reactpy.backend.*.configure(...)` calls currently require a component. However, our main method telling users how to use ReactPy should involve using our [template tag](https://github.com/reactive-python/reactpy/issues/653).

### Proposed Actions

Either remove component as a parameter, or make it an optional parameter.

Frankly, the current method of artificially setting up an index route is useless or gimmicky at best.

**Comment by rmorshea** [comment]
> However, our main method telling users how to use ReactPy should involve using our https://github.com/reactive-python/reactpy/issues/653... Frankly, the current method of artificially setting up an index route is useless or gimmicky at best.

Can you give some more detail around the problems with the current implementation and how using using template tags would solve them?

**Comment by Archmonger** [comment]
Mounting a `configure(... , component = ...)` at the index route clashes with that "embed within existing projects" concept. We're indirectly suggesting to users "You either create your whole app in ReactPy, or you don't". But unfortunately, the template tag is needed so we don't force users to write their own JS clients.

Right now there is a lot of necessary SPA browser features that can't be done with ReactPy.

The `configure()` function is ineffective for embedding within existing applications compared to `reactpy-django`. Our SPA support isn't really useable until we have Python support for 

- File Uploads
- ReactJS packages (in a convenient way)
- Browser cookies
- Sessions
- IndexDB
- WebSQL
- Push Messaging
- Background Sync
- Forward Cache
- Local Storage
- Service Workers
- Web manifests

Practically everything under `Chrome Devtools -> Application` is going to need native integration if we want to advertise SPAs as a realistic dev scenario. Getting there is going to require a lot of dev hours, so we won't reach it quickly.

Since our SPA support is practically unusable, the only "real world" use cases we can actually support is embedding via template tags.

**Comment by Archmonger** [comment]
Closing this in favor of #1110
