### ISSUE TITLE
ImportError: cannot import name 'component' from partially initialized module 'reactpy' (most likely due to a circular import)

### ISSUE THREAD

**Issue by muhammadd8** [reactive-python/reactpy#1122]
### Current Situation

from reactpy import component, html, run

@component
def hello_world():
    return html.h1("Hello, World!")

run(hello_world)

when i execute this test code, it gives me the error below
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dev/Desktop/AIML/reactpy.py", line 1, in <module>
    from reactpy import component
ImportError: cannot import name 'component' from partially initialized module 'reactpy' (most likely due to a circular import) (/home/dev/Desktop/AIML/reactpy.py)

reactpy is installed and sample application pages is opening as well. 
kindly tell how to cater this issue?

**Comment by Archmonger** [comment]
You cannot name your Python file `reactpy`, otherwise you are redefining where `from reactpy ...` imports from.

Please change your file name.
