### ISSUE TITLE
Cannot use flask integration due to outdated markupsafe dependency

### ISSUE THREAD

**Issue by rmorshea** [reactive-python/reactpy#1163]
### Discussed in https://github.com/reactive-python/reactpy/discussions/1162

<div type='discussions-op-text'>

<sup>Originally posted by **ppalucha** November 11, 2023</sup>
Hi,
I'm trying to install `reactpy[flask]` in my project, but current versions of flask (2.3.3) depend on markupsafe >= 2.1.1 and reacty[flask] requires markupsafe < 2.1. 
What would be required to update this dependency version? Is there a specific reason version < 2.1 is required.</div>

**Comment by Archmonger** [comment]
Closing in favor of #1110
