### ISSUE TITLE
`event["target"]` value for radio input and checkboxes is always `'on'`

### ISSUE THREAD

**Issue by Archmonger** [reactive-python/reactpy#1188]
### Current Situation

The `value` for any serialized checkbox or radio button is always `on` when viewed within an `event["target"]`. This effectively makes them unusable within a form's `on_submit` event.

### Proposed Actions

Fix how we serialize these input fields, and look for any other outliers that might exist.

**Comment by zx013** [comment]
If set value xxx in radio input, the value always be xxx. So I can not get which radio input I choose.
