### ISSUE TITLE
Automatically convert JS hooks to IDOM hooks

### ISSUE THREAD

**Issue by Archmonger** [reactive-python/reactpy#541]
### Current Situation

Hooks within react libraries, for example, [usePagination](https://react-table.tanstack.com/docs/api/usePagination) hook within React-Table currently need to be manually rewritten in order to function in IDOM.

### Proposed Changes

Investigate whether JS hooks can automatically be converted to Python hooks in some situations.

### Implementation Details

See if transpilers, such as [Js2Py](https://github.com/PiotrDabkowski/Js2Py) can be used to convert hooks automatically.

Or if we can somehow wrap the hook javascript and inject some `client <-> server` handler logic on-top.

**Comment by rmorshea** [comment]
This might be the preferred way to accomplish this: https://blog.pyodide.org/posts/react-in-python-with-pyodide/

**Comment by Archmonger** [comment]
Closing this in favor of #786
