### ISSUE TITLE
Rewrite client with Typescript

### ISSUE THREAD

**Issue by rmorshea** [reactive-python/reactpy#743]
### Current Situation

Currently IDOM's client is implemented in Vanilla JS. This makes it easy to develop and contribute to, but the code-base is growing in complexity, and without unit tests, there's some risk that it will become difficult to maintain.

### Proposed Actions

Rewrite the client using typescript. Type annotations seem to be [coming to browser Javascript engines](https://github.com/tc39/proposal-type-annotations) soon so, like with Python, typed Javascript is likely to grow in popularity. Type annotations are not a replacement for unit tests, but they will help. It will also be a form of documentation that can be referred to by new contributors and users.

**Comment by Archmonger** [comment]
Should we switch to TS, or simply wait for JavaScript to support type hints?

**Comment by rmorshea** [comment]
I'm not really sure how it's going to pan out, but from my understanding, they're not re-inventing the wheel - the syntax is identical to TS so if we wrote in TS it should work as-is in the future.
