### ISSUE TITLE
Do Not Unmount Old View On Reconnect

### ISSUE THREAD

**Issue by rmorshea** [reactive-python/reactpy#760]
### Current Situation

Presently, upon reconnecting, the client [unmounts the old view and mounts a new one](https://github.com/idom-team/idom/blob/d1a69f676be43da15c9d2c7c419f55e4acb10ef5/src/client/packages/idom-client-react/src/mount.js#L42). This results in a brief, but jarring flash as the new view loads.

### Proposed Actions

Instead of unmounting the old view we can simply retain it. The first message from the server should be the new VDOM which should be set at the root. This will cause React to render the full tree of components, but it will prevent the view from flashing from the user's perspective.

**Comment by Archmonger** [comment]
Could not unmounting the view cause a memory leak?

**Comment by rmorshea** [comment]
I don't think so. As a note for this issue, it looks like `ReactDOM.render` is deprecated in favor of `createRoot` which returns an object with `render` and `unmount` methods. This seems to rather explicitly allow for `render` to be called multiple times as we'd want to do here.

**Comment by Archmonger** [comment]
This issue was resolved in #886 and #901.

There is still the separate issue of the initial `mount` deleting the inner contents of the div, which can complicate #578.

Closing this issue.
