### ISSUE TITLE
Remove usage of import_module in idom.run

### ISSUE THREAD

**Issue by rmorshea** [reactive-python/reactpy#764]
### Current Situation

There was a [bug in `idom.run`](https://github.com/idom-team/idom/pull/763) because we failed to update an import after a name change.

### Proposed Actions

We used `import_module("idom.backend.default")` presumably because it was syntactically convenient to write [this](https://github.com/idom-team/idom/blob/main/src/idom/backend/utils.py#L43). Instead we should just do an actual import:

```python
if not implementation:  # pragma: no cover
    from idom.backend import default as implementation
```

**Comment by Archmonger** [comment]
Closing this in favor of #1113
