### ISSUE TITLE
Transmit React `client.js` warnings/errors to Python logger

### ISSUE THREAD

**Issue by Archmonger** [reactive-python/reactpy#816]
### Current Situation

Currently, all warnings or exceptions generated within the react client are only displayed on the front-end. There is a reasonable expectation that most users aren't always going to be looking at inspect tools. Thus, when developing problematic IDOM code there is often no visual indication of what issues arise, leading to a confusing developer experience.

For example, warnings like ```client.js:3636 Warning: Invalid DOM property `class`. Did you mean `className`?``` should be transmitted to Python.

The fact that these issues aren't displayed in Python feels a bit disjointed for a **Python** web development framework.

### Proposed Actions

Catch all warnings/exceptions from `client.js` and transmit them to a Python logger via websockets.

**Comment by rmorshea** [comment]
Related to #346

**Comment by Archmonger** [comment]
Closing in favor of #890
