### ISSUE TITLE
Stale event handlers can reside in the client

### ISSUE THREAD

**Issue by Archmonger** [reactive-python/reactpy#896]
### Current Situation

A consequence of [this change](https://github.com/idom-team/idom/pull/886) is that now stale event handlers can stay within the client.

To replicate, restart the ASGI webserver while keeping an IDOM tab open. This will silently breaks all event handlers on reconnect.

```
2023-01-28T23:57:45-0800 | INFO | Ignored event - handler '3d35445264fb4d79a821e59f5961fc43' does not exist or its component unmounted
```

### Proposed Actions

Look into the following
- Is there a way of unmounting a React component that doesn't delete the DOM tree?
   - We might want to peek at the `ReactDOM.unmountComponentAtNode` source code and determine if we can do this 
- Can we potentially refresh all handlers within the client on reconnect?
- Do we need to revert this PR?

**Comment by Archmonger** [comment]
I would say resolving this would be the final issue issue to our first `Production/Stable` release.

As far as I've tested over the last 1.5 years, it looks like the package will now be  bug-free!

**Comment by rmorshea** [comment]
I'm thinking that I basically just revert the change for now. I'm realizing that fixing it for real may actually be more complicated than I thought. Will reopen the original issue, mark for (v2 or whatever subsequent milestone), and add link this issue.

**Comment by rmorshea** [comment]
As part of that reversion I'll [modify this test](https://github.com/idom-team/idom/blob/cc723dea43003bbe21f80468fb31f8c1b855f0ee/tests/test_client.py#L16) to catch this problem in the future.
