### ISSUE TITLE
`idom update-html-usages` CLI does not work

### ISSUE THREAD

**Issue by Archmonger** [reactive-python/reactpy#898]
### Current Situation

It looks like the CLI is not accessible within my Windows venv after `pip install idom==1.0.0a1`.

### Proposed Actions

Determine why and fix before the 1.0.0 release.

**Comment by rmorshea** [comment]
Are you able to access it via `python -m idom`?

**Comment by rmorshea** [comment]
Can confirm that accessing directly via `idom` is broken for me though.

**Comment by Archmonger** [comment]
This seems to be how Django [registers their `django-admin` CLI command.](https://github.com/django/django/blob/20a0850099340fb4cb8df0e4441e5019b2cbd1ea/setup.cfg#L44)

**Comment by Archmonger** [comment]
> Are you able to access it via `python -m idom`?

Yep that works
