### ISSUE TITLE
Update Web Module Examples

### ISSUE THREAD

**Issue by rmorshea** [reactive-python/reactpy#905]
### Current Situation

The auto-convert utility does not know how to convert usages of exported web modules. As such, some example in the docs need to be manually updated: https://github.com/idom-team/idom/tree/main/docs/source/guides/escape-hatches/_examples

### Proposed Actions

Fix them

**Comment by Archmonger** [comment]
Is this still open?

**Comment by rmorshea** [comment]
nope
