### ISSUE TITLE
Add warning for `html.script`

### ISSUE THREAD

**Issue by Archmonger** [reactive-python/reactpy#924]
### Current Situation

Currently, there is no documented warnings for the potential of XSS attacks when using `html.script`

### Proposed Actions

We should add a disclaimer to warn users not to use raw user inputs (from any untrusted data source) within the script contents to avoid XSS attacks.

**Comment by ZEUS-03** [comment]
Can you assign me the task? Will be a good starting point.

**Comment by Archmonger** [comment]
We don't utilize the issue assignment feature on GitHub. The first person to open a draft PR gets priority to resolve it.

**Comment by ZEUS-03** [comment]
ok thanks! will do that.

**Comment by rmorshea** [comment]
@Archmonger, was your intention for this to be in the docstring.

**Comment by Archmonger** [comment]
Yeah, since the docstring gets turned into auto-docs.

**Comment by ZEUS-03** [comment]
hey! can you please tell me where do i have to put or write the documention i mean in which file?

**Comment by rmorshea** [comment]
https://github.com/reactive-python/reactpy/blob/main/src/reactpy/html.py

**Comment by rmorshea** [comment]
@Archmonger, can we create a follow-up ticket for a tool that would sanitize inputs to scripts? I think we can do more to help mitigate this risk for users.

**Comment by Archmonger** [comment]
You think this could be added to our flake8 plugin?

**Comment by rmorshea** [comment]
It's possible, but if that's all we supplied users might improperly sanitize inputs. Better to provide a standardized solution.

**Comment by Archmonger** [comment]
That might be a bit over engineered for a tag that we shouldn't incentivize using.

In my opinion, due to script tags being inherently dangerous we should treat them similar to React `dangerouslySetInnerHtml`.

It's best to get the idea into user's heads that "you can use this but it's risky so you probably shouldn't."

**Comment by rmorshea** [comment]
I like that idea. We could require the script to be passed as a kwarg with a scary name like `insecurely_eval` or something.
