### ISSUE TITLE
Rewrite Client in TypeScript

### ISSUE THREAD

**Issue by rmorshea** [reactive-python/reactpy#929]
### Current Situation

Currently, the client is written in Vanilla JavaScript. While this makes it easier to contribute to for those who are new to Javascript, it makes the codebase harder to scale as things get more complicated. As it stands now things are manageable for me, but that's probably because I have all the context built up in my head. For someone who's new, I suspect types would make the codebase more understandable.

### Proposed Actions

Unfortunately with TypeScript there's no way to do progressive typing (from what I understand) so the whole thing would have to be rewritten from scratch. Given that, I think there are some interfaces that could be improved in the process. Specifically, the concept of passing a callback when mounting the root component in order to capture the update hook. Even explaining that sounds odd - it's a callback to register a callback 🙃 . It would be much more convenient if the interface leveraged async functions so you could do the following:

```javascript
view = createView({...});
await mount.update({...});
await mount.event();
```

**Comment by Archmonger** [comment]
Issue already exists #743
