### ISSUE TITLE
Use `poetry` to pin docs dependencies

### ISSUE THREAD

**Issue by rmorshea** [reactive-python/reactpy#964]
### Current Situation

Dependencies in the container running the docs are not pinned. This can cause issues with stability.

### Proposed Actions

Use [`poetry`](https://python-poetry.org/) to create a reproducible docs environment in `docs/pyproject.toml`.

**Comment by ZEUS-03** [comment]
can you please elaborate the issue?

**Comment by Archmonger** [comment]
The package versions in [this file](https://github.com/reactive-python/reactpy/blob/main/requirements/build-docs.txt) need to be pinned, so that when the docs are released we won't run into unexpected build failures.

**Comment by ZEUS-03** [comment]
Can you assign me the issue?

**Comment by rmorshea** [comment]
I'm realizing that a better solution to this problem would be to have a lockfile. Using `pip freeze` has [a lot of problems](https://alexo.dev/blog/avoiding-pip-freeze-2/). Unfortunately there aren't any standards around lock files (and there [won't be for some time](https://peps.python.org/pep-0665/)). The most popular solution to this problem is [Poetry](https://python-poetry.org/). The plan then would involve setting up a `docs/pyproject.toml` file and treating the docs as a proper "application".

Apologies @ZEUS-03, with this change of plans, I'd say this isn't really a "good first issue" anymore.

**Comment by ZEUS-03** [comment]
@rmorshea learned a lot! Thanks for the opportunity.

**Comment by rmorshea** [comment]
BTW @ZEUS-03, if you're interested in making other contributions I make myself available for [office hours](https://github.com/reactive-python/reactpy/discussions/312) twice a week. If those times don't work, start a discussion and we can find a time.

**Comment by ZEUS-03** [comment]
yeah! sure.
