### ISSUE TITLE
Follow NEP 29 (Drop Python 3.7 and 3.8)

### ISSUE THREAD

**Issue by rmorshea** [reactive-python/reactpy#977]
### Current Situation

We should follow Numpy's Python version compatibility policy ([NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)) which states that packages should "support at least all minor versions of Python introduced and released in the prior 42 months from the anticipated release date". In general this means that we will always support the last 3-4 minor releases of Python.

### Proposed Actions

Drop support for Python 3.7 and 3.8 and document this policy.

**Comment by Archmonger** [comment]
Already resolved within a previous PR.
